### ISSUE TITLE
JuliaRegistrator

### ISSUE THREAD

**Issue by fercarozzi** [SeismicJulia/SeisReconstruction.jl#9]
@JuliaRegistrator register()

**Comment by fercarozzi** [comment]
@JuliaRegistrator register()

**Comment by fercarozzi** [comment]
@JuliaRegistrator register()

**Comment by fercarozzi** [comment]
@JuliaRegistrator register()

**Comment by AtilaSaraiva** [comment]
@JuliaRegistrator register()

**Comment by AtilaSaraiva** [comment]
@JuliaRegistrator register()

**Comment by AtilaSaraiva** [comment]
@JuliaRegistrator register()

**Comment by AtilaSaraiva** [comment]
@JuliaRegistrator register()

**Comment by AtilaSaraiva** [comment]
@JuliaRegistrator register()
